s = set()
n1 = input("Enter the number 1: \n")
s.add(int(n1))
n2 = input("Enter the number 2: \n")
s.add(int(n2))
n3 = input("Enter the number 3: \n")
s.add(int(n3))
n4 = input("Enter the number 4: \n")
s.add(int(n4))
n5 = input("Enter the number 5: \n")
s.add(n5)
n6 = input("Enter the number 6: \n")
s.add(int(n6))
n7 = input("Enter the number 7: \n")
s.add(int(n7))
n8 = input("Enter the number 8: \n")
s.add(int(n8))

print(s)